### ISSUE TITLE
cannot launch newest version

### ISSUE THREAD

**Issue by purpleuv** [timas130/SitsEndAnchor#1]
normally I can decipher the fabric error messages but I don't quite understand this one, every time i try to launch this mod I get this message. I have tested the mod multiple times on its own with the vanilla launcher and otherwise and keep getting this code, even though this is the newest version

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Sit's End Anchor' (endanchor) ${version} with any version that is compatible with:
		 - fabricloader 0.15.3
		 - minecraft 1.20.4
More details:
	 - Mod 'Sit's End Anchor' (endanchor) ${version} requires version ${loader_version} of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.15.3!
	 - Mod 'Sit's End Anchor' (endanchor) ${version} requires version ${minecraft_version} of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by timas130** [comment]
Hello! Thanks for bringing this up. Looks like I messed up a bit when uploading the mod. You should visit [the full version page](https://modrinth.com/mod/endanchor/version/1.0.0) on Modrinth and download the ~~second~~ first file (`SitsEndAnchor-1.0.0.jar` *without* `-sources`).

What happened was that I uploaded the sources first, and only then the actual compiled mod. Thus, Modrinth set the sources as the default file for download. I'll fix that right now.

Again, thanks for letting me know.

**Comment by timas130** [comment]
I have fixed it. Just redownload the mod now and it should work. Don't forget to delete the `-sources` version. Let me know if this works.

**Comment by purpleuv** [comment]
Thanks! It works perfect now
