### ISSUE TITLE
Idea to allow for recipe customization

### ISSUE THREAD

**Issue by The13thEmpire** [timas130/SitsEndAnchor#3]
I'm making assumptions based on the source. It appears you have the recipe hard-coded so you can pull the destination data from the lodestone compass. 

What if the outer 8 items could be set via mod config.

**Comment by timas130** [comment]
I'll take a look at it tomorrow.

**Comment by The13thEmpire** [comment]
alternitively you might be able to make the recipe data driven and just force the center to be a lodestone compass.

**Comment by timas130** [comment]
Added in 1.1.0 (Modrinth: [MC 1.21](https://modrinth.com/mod/endanchor/version/1.1.0), [MC 1.21.1](https://modrinth.com/mod/endanchor/version/ly04w9HI))
